# Generated by Django 4.0.4 on 2022-04-16 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('tel', models.IntegerField(max_length=11)),
                ('age', models.IntegerField(max_length=11)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
                ('purchaseDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='sells',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('productId', models.IntegerField(max_length=11)),
                ('personId', models.IntegerField(max_length=11)),
                ('sellCode', models.IntegerField(max_length=11)),
            ],
        ),
    ]
