# Generated by Django 4.0.4 on 2022-05-10 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='purchaseDate',
        ),
        migrations.AddField(
            model_name='sells',
            name='purchaseDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
