# Generated by Django 4.0.4 on 2022-05-10 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_remove_products_purchasedate_sells_purchasedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='id',
            new_name='personId',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='id',
            new_name='productId',
        ),
        migrations.AlterField(
            model_name='sells',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id', to='emails.persons'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id', to='emails.products'),
        ),
    ]
