# Generated by Django 4.0.4 on 2022-05-10 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_rename_id_persons_personid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sells',
            old_name='id',
            new_name='sellId',
        ),
    ]
