# Generated by Django 4.0.4 on 2022-05-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_sells_personid_alter_sells_productid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='lastname',
            new_name='plastname',
        ),
        migrations.RenameField(
            model_name='persons',
            old_name='name',
            new_name='pname',
        ),
        migrations.RenameField(
            model_name='sells',
            old_name='personId',
            new_name='spersonId',
        ),
        migrations.RenameField(
            model_name='sells',
            old_name='productId',
            new_name='sproductId',
        ),
    ]
