# Generated by Django 4.0.4 on 2022-05-10 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_rename_lastname_persons_plastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='purchaseDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='products',
            name='spersonId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='sells', to='emails.persons'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='sells',
        ),
    ]
