# Generated by Django 4.0.4 on 2022-05-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_products_purchasedate_products_spersonid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='spersonId',
        ),
    ]
