# Generated by Django 4.0.4 on 2022-05-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_remove_products_spersonid'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='spersonId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='sells', to='emails.persons'),
        ),
    ]
