# Generated by Django 4.0.4 on 2022-05-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_products_spersonid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Productos',
        ),
    ]
